package tables;

import java.util.*;

/**
 * Created by hosainfathelbab on 4/4/15.
 * for more informatio about the table
 * https://docs.google.com/spreadsheets/d/1VvrbGsTwVNcZjjhy2eZS0iTTVccEljAL6twJRdjO1bQ/edit?usp=sharing
 */
public class Grade2Table {

    private static Set<Grade2Abbreviation> grade2Table;

    static{
        grade2Table = new HashSet<Grade2Abbreviation>();

        grade2Table.add(new Grade2Abbreviation().setWord("أو").setSymbol("⠁"));
        grade2Table.add(new Grade2Abbreviation().setWord("بل").setSymbol("⠃"));
        grade2Table.add(new Grade2Abbreviation().setWord("برمج").setSymbol("⠈⠃"));
        grade2Table.add(new Grade2Abbreviation().setWord("بعد").setSymbol("⠐⠃"));
        grade2Table.add(new Grade2Abbreviation().setWord("بعيد").setSymbol("⠘⠃"));
        grade2Table.add(new Grade2Abbreviation().setWord("برنامج").setSymbol("⠸⠃"));
        grade2Table.add(new Grade2Abbreviation().setWord("تلك").setSymbol("⠞"));
        grade2Table.add(new Grade2Abbreviation().setWord("تعليم").setSymbol("⠈⠞"));
        grade2Table.add(new Grade2Abbreviation().setWord("تحت").setSymbol("⠐⠞"));
        grade2Table.add(new Grade2Abbreviation().setWord("تدريب").setSymbol("⠘⠞"));
        grade2Table.add(new Grade2Abbreviation().setWord("تدريج").setSymbol("⠸⠞"));
        grade2Table.add(new Grade2Abbreviation().setWord("ثم").setSymbol("⠹"));
        grade2Table.add(new Grade2Abbreviation().setWord("ثقاف").setSymbol("⠈⠹"));
        grade2Table.add(new Grade2Abbreviation().setWord("أثناء").setSymbol("⠐⠹"));
        grade2Table.add(new Grade2Abbreviation().setWord("ثاني").setSymbol("⠘⠹"));
        grade2Table.add(new Grade2Abbreviation().setWord("ثالث").setSymbol("⠸⠹"));
        grade2Table.add(new Grade2Abbreviation().setWord("جدا").setSymbol("⠚"));
        grade2Table.add(new Grade2Abbreviation().setWord("جديد").setSymbol("⠈⠚"));
        grade2Table.add(new Grade2Abbreviation().setWord("جميع").setSymbol("⠐⠚"));
        grade2Table.add(new Grade2Abbreviation().setWord("جانب").setSymbol("⠘⠚"));
        grade2Table.add(new Grade2Abbreviation().setWord("جعل").setSymbol("⠸⠚"));
        grade2Table.add(new Grade2Abbreviation().setWord("حتى").setSymbol("⠱"));
        grade2Table.add(new Grade2Abbreviation().setWord("أحيان").setSymbol("⠈⠱"));
        grade2Table.add(new Grade2Abbreviation().setWord("حياة").setSymbol("⠐⠱"));
        grade2Table.add(new Grade2Abbreviation().setWord("حقيق").setSymbol("⠘⠱"));
        grade2Table.add(new Grade2Abbreviation().setWord("حول").setSymbol("⠸⠱"));
        grade2Table.add(new Grade2Abbreviation().setWord("خير").setSymbol("⠭"));
        grade2Table.add(new Grade2Abbreviation().setWord("خروج").setSymbol("⠈⠭"));
        grade2Table.add(new Grade2Abbreviation().setWord("خصوص").setSymbol("⠐⠭"));
        grade2Table.add(new Grade2Abbreviation().setWord("خارج").setSymbol("⠘⠭"));
        grade2Table.add(new Grade2Abbreviation().setWord("خاصة").setSymbol("⠸⠭"));
        grade2Table.add(new Grade2Abbreviation().setWord("دخول").setSymbol("⠙"));
        grade2Table.add(new Grade2Abbreviation().setWord("دقيق").setSymbol("⠈⠙"));
        grade2Table.add(new Grade2Abbreviation().setWord("دائم").setSymbol("⠐⠙"));
        grade2Table.add(new Grade2Abbreviation().setWord("داخل").setSymbol("⠘⠙"));
        grade2Table.add(new Grade2Abbreviation().setWord("دليل").setSymbol("⠸⠙"));
        grade2Table.add(new Grade2Abbreviation().setWord("ذاكر").setSymbol("⠮"));
        grade2Table.add(new Grade2Abbreviation().setWord("ذاهب").setSymbol("⠈⠮"));
        grade2Table.add(new Grade2Abbreviation().setWord("ذلك").setSymbol("⠐⠮"));
        grade2Table.add(new Grade2Abbreviation().setWord("حينئذ").setSymbol("⠘⠮"));
        grade2Table.add(new Grade2Abbreviation().setWord("عندئذ").setSymbol("⠸⠮"));
        grade2Table.add(new Grade2Abbreviation().setWord("ربما").setSymbol("⠗"));
        grade2Table.add(new Grade2Abbreviation().setWord("رياض").setSymbol("⠈⠗"));
        grade2Table.add(new Grade2Abbreviation().setWord("روح").setSymbol("⠐⠗"));
        grade2Table.add(new Grade2Abbreviation().setWord("رئيس").setSymbol("⠘⠗"));
        grade2Table.add(new Grade2Abbreviation().setWord("رسول").setSymbol("⠸⠗"));
        grade2Table.add(new Grade2Abbreviation().setWord("زاول").setSymbol("⠵"));
        grade2Table.add(new Grade2Abbreviation().setWord("زواج").setSymbol("⠈⠵"));
        grade2Table.add(new Grade2Abbreviation().setWord("زمان").setSymbol("⠐⠵"));
        grade2Table.add(new Grade2Abbreviation().setWord("زمن").setSymbol("⠘⠵"));
        grade2Table.add(new Grade2Abbreviation().setWord("زوج").setSymbol("⠸⠵"));
        grade2Table.add(new Grade2Abbreviation().setWord("سوف").setSymbol("⠎"));
        grade2Table.add(new Grade2Abbreviation().setWord("سياس").setSymbol("⠈⠎"));
        grade2Table.add(new Grade2Abbreviation().setWord("سريع").setSymbol("⠐⠎"));
        grade2Table.add(new Grade2Abbreviation().setWord("سائر").setSymbol("⠘⠎"));
        grade2Table.add(new Grade2Abbreviation().setWord("سبيل").setSymbol("⠸⠎"));
        grade2Table.add(new Grade2Abbreviation().setWord("شيء").setSymbol("⠩"));
        grade2Table.add(new Grade2Abbreviation().setWord("شيئا").setSymbol("⠈⠩"));
        grade2Table.add(new Grade2Abbreviation().setWord("شديد").setSymbol("⠐⠩"));
        grade2Table.add(new Grade2Abbreviation().setWord("شاهد").setSymbol("⠘⠩"));
        grade2Table.add(new Grade2Abbreviation().setWord("شؤون").setSymbol("⠸⠩"));
        grade2Table.add(new Grade2Abbreviation().setWord("صار").setSymbol("⠯"));
        grade2Table.add(new Grade2Abbreviation().setWord("صديق").setSymbol("⠈⠯"));
        grade2Table.add(new Grade2Abbreviation().setWord("صاحب").setSymbol("⠐⠯"));
        grade2Table.add(new Grade2Abbreviation().setWord("صغير").setSymbol("⠘⠯"));
        grade2Table.add(new Grade2Abbreviation().setWord("صور").setSymbol("⠸⠯"));
        grade2Table.add(new Grade2Abbreviation().setWord("أيضا").setSymbol("⠫"));
        grade2Table.add(new Grade2Abbreviation().setWord("ضعيف").setSymbol("⠈⠫"));
        grade2Table.add(new Grade2Abbreviation().setWord("ضمير").setSymbol("⠐⠫"));
        grade2Table.add(new Grade2Abbreviation().setWord("بعض").setSymbol("⠘⠫"));
        grade2Table.add(new Grade2Abbreviation().setWord("ضرور").setSymbol("⠸⠫"));
        grade2Table.add(new Grade2Abbreviation().setWord("فقط").setSymbol("⠾"));
        grade2Table.add(new Grade2Abbreviation().setWord("طبيع").setSymbol("⠈⠾"));
        grade2Table.add(new Grade2Abbreviation().setWord("طريق").setSymbol("⠐⠾"));
        grade2Table.add(new Grade2Abbreviation().setWord("طبع").setSymbol("⠘⠾"));
        grade2Table.add(new Grade2Abbreviation().setWord("طويل").setSymbol("⠸⠾"));
        grade2Table.add(new Grade2Abbreviation().setWord("ظهر").setSymbol("⠿"));
        grade2Table.add(new Grade2Abbreviation().setWord("حافظ").setSymbol("⠈⠿"));
        grade2Table.add(new Grade2Abbreviation().setWord("ظاهر").setSymbol("⠐⠿"));
        grade2Table.add(new Grade2Abbreviation().setWord("ظروف").setSymbol("⠘⠿"));
        grade2Table.add(new Grade2Abbreviation().setWord("ظهور").setSymbol("⠸⠿"));
        grade2Table.add(new Grade2Abbreviation().setWord("عسى").setSymbol("⠷"));
        grade2Table.add(new Grade2Abbreviation().setWord("عادة").setSymbol("⠈⠷"));
        grade2Table.add(new Grade2Abbreviation().setWord("عزيز").setSymbol("⠐⠷"));
        grade2Table.add(new Grade2Abbreviation().setWord("عبارة").setSymbol("⠘⠷"));
        grade2Table.add(new Grade2Abbreviation().setWord("عظيم").setSymbol("⠸⠷"));
        grade2Table.add(new Grade2Abbreviation().setWord("غاية").setSymbol("⠣"));
        grade2Table.add(new Grade2Abbreviation().setWord("غادر").setSymbol("⠈⠣"));
        grade2Table.add(new Grade2Abbreviation().setWord("غير").setSymbol("⠐⠣"));
        grade2Table.add(new Grade2Abbreviation().setWord("غالب").setSymbol("⠘⠣"));
        grade2Table.add(new Grade2Abbreviation().setWord("غريب").setSymbol("⠸⠣"));
        grade2Table.add(new Grade2Abbreviation().setWord("فلما").setSymbol("⠋"));
        grade2Table.add(new Grade2Abbreviation().setWord("فراغ").setSymbol("⠈⠋"));
        grade2Table.add(new Grade2Abbreviation().setWord("فوق").setSymbol("⠐⠋"));
        grade2Table.add(new Grade2Abbreviation().setWord("فائدة").setSymbol("⠘⠋"));
        grade2Table.add(new Grade2Abbreviation().setWord("فعل").setSymbol("⠸⠋"));
        grade2Table.add(new Grade2Abbreviation().setWord("قرب").setSymbol("⠟"));
        grade2Table.add(new Grade2Abbreviation().setWord("قطع").setSymbol("⠈⠟"));
        grade2Table.add(new Grade2Abbreviation().setWord("قليل").setSymbol("⠐⠟"));
        grade2Table.add(new Grade2Abbreviation().setWord("قريب").setSymbol("⠘⠟"));
        grade2Table.add(new Grade2Abbreviation().setWord("قديم").setSymbol("⠸⠟"));
        grade2Table.add(new Grade2Abbreviation().setWord("كيف").setSymbol("⠅"));
        grade2Table.add(new Grade2Abbreviation().setWord("كتاب").setSymbol("⠈⠅"));
        grade2Table.add(new Grade2Abbreviation().setWord("كثير").setSymbol("⠐⠅"));
        grade2Table.add(new Grade2Abbreviation().setWord("كبير").setSymbol("⠘⠅"));
        grade2Table.add(new Grade2Abbreviation().setWord("كاتب").setSymbol("⠸⠅"));
        grade2Table.add(new Grade2Abbreviation().setWord("ليس").setSymbol("⠇"));
        grade2Table.add(new Grade2Abbreviation().setWord("لطيف").setSymbol("⠈⠇"));
        grade2Table.add(new Grade2Abbreviation().setWord("لكن").setSymbol("⠐⠇"));
        grade2Table.add(new Grade2Abbreviation().setWord("لعل").setSymbol("⠘⠇"));
        grade2Table.add(new Grade2Abbreviation().setWord("لسان").setSymbol("⠸⠇"));
        grade2Table.add(new Grade2Abbreviation().setWord("مثل").setSymbol("⠍"));
        grade2Table.add(new Grade2Abbreviation().setWord("مكفوف").setSymbol("⠈⠍"));
        grade2Table.add(new Grade2Abbreviation().setWord("مرة").setSymbol("⠐⠍"));
        grade2Table.add(new Grade2Abbreviation().setWord("معنى").setSymbol("⠘⠍"));
        grade2Table.add(new Grade2Abbreviation().setWord("معظم").setSymbol("⠸⠍"));
        grade2Table.add(new Grade2Abbreviation().setWord("نحو").setSymbol("⠝"));
        grade2Table.add(new Grade2Abbreviation().setWord("ناسب").setSymbol("⠈⠝"));
        grade2Table.add(new Grade2Abbreviation().setWord("نفس").setSymbol("⠐⠝"));
        grade2Table.add(new Grade2Abbreviation().setWord("ناحية").setSymbol("⠘⠝"));
        grade2Table.add(new Grade2Abbreviation().setWord("نعم").setSymbol("⠸⠝"));
        grade2Table.add(new Grade2Abbreviation().setWord("هناك").setSymbol("⠓"));
        grade2Table.add(new Grade2Abbreviation().setWord("هكذا").setSymbol("⠈⠓"));
        grade2Table.add(new Grade2Abbreviation().setWord("هذا").setSymbol("⠐⠓"));
        grade2Table.add(new Grade2Abbreviation().setWord("هذه").setSymbol("⠘⠓"));
        grade2Table.add(new Grade2Abbreviation().setWord("هؤلاء").setSymbol("⠸⠓"));
        grade2Table.add(new Grade2Abbreviation().setWord("ولما").setSymbol("⠺"));
        grade2Table.add(new Grade2Abbreviation().setWord("وارد").setSymbol("⠈⠺"));
        grade2Table.add(new Grade2Abbreviation().setWord("واحد").setSymbol("⠐⠺"));
        grade2Table.add(new Grade2Abbreviation().setWord("واجب").setSymbol("⠘⠺"));
        grade2Table.add(new Grade2Abbreviation().setWord("وجود").setSymbol("⠸⠺"));
        grade2Table.add(new Grade2Abbreviation().setWord("لا سيما").setSymbol("⠈⠧"));
        grade2Table.add(new Grade2Abbreviation().setWord("لا شك").setSymbol("⠐⠧"));
        grade2Table.add(new Grade2Abbreviation().setWord("لا بد").setSymbol("⠘⠧"));
        grade2Table.add(new Grade2Abbreviation().setWord("لا يزال").setSymbol("⠸⠧"));
        grade2Table.add(new Grade2Abbreviation().setWord("يوم").setSymbol("⠊"));
        grade2Table.add(new Grade2Abbreviation().setWord("يسير").setSymbol("⠈⠊"));
        grade2Table.add(new Grade2Abbreviation().setWord("أيام").setSymbol("⠐⠊"));
        grade2Table.add(new Grade2Abbreviation().setWord("يمكن").setSymbol("⠘⠊"));
        grade2Table.add(new Grade2Abbreviation().setWord("يقول").setSymbol("⠸⠊"));
        grade2Table.add(new Grade2Abbreviation().setWord("على").setSymbol("⠕"));
        grade2Table.add(new Grade2Abbreviation().setWord("أعلى").setSymbol("⠐⠕"));
        grade2Table.add(new Grade2Abbreviation().setWord("أولى").setSymbol("⠠⠕"));
        grade2Table.add(new Grade2Abbreviation().setWord("أدنى").setSymbol("⠠⠕"));
        grade2Table.add(new Grade2Abbreviation().setWord("أخرى").setSymbol("⠘⠕"));
        grade2Table.add(new Grade2Abbreviation().setWord("أغنى").setSymbol("⠰⠕"));
        grade2Table.add(new Grade2Abbreviation().setWord("أقصى").setSymbol("⠸⠕"));
        grade2Table.add(new Grade2Abbreviation().setWord("قبل").setSymbol("⠡"));
        grade2Table.add(new Grade2Abbreviation().setWord("جملة").setSymbol("⠈⠡"));
        grade2Table.add(new Grade2Abbreviation().setWord("ساعة").setSymbol("⠐⠡"));
        grade2Table.add(new Grade2Abbreviation().setWord("تارة").setSymbol("⠘⠡"));
        grade2Table.add(new Grade2Abbreviation().setWord("تربية").setSymbol("⠰⠡"));
        grade2Table.add(new Grade2Abbreviation().setWord("لحظة").setSymbol("⠸⠡"));
        grade2Table.add(new Grade2Abbreviation().setWord("قد").setSymbol("⠄"));
        grade2Table.add(new Grade2Abbreviation().setWord("أسئلة").setSymbol("⠌"));
        grade2Table.add(new Grade2Abbreviation().setWord("أكبر").setSymbol("⠈⠌"));
        grade2Table.add(new Grade2Abbreviation().setWord("أحد").setSymbol("⠐⠌"));
        grade2Table.add(new Grade2Abbreviation().setWord("أسفل").setSymbol("⠠⠌"));
        grade2Table.add(new Grade2Abbreviation().setWord("أخير").setSymbol("⠘⠌"));
        grade2Table.add(new Grade2Abbreviation().setWord("أصغر").setSymbol("⠰⠌"));
        grade2Table.add(new Grade2Abbreviation().setWord("أكثر").setSymbol("⠸⠌"));
        grade2Table.add(new Grade2Abbreviation().setWord("أولئك").setSymbol("⠳"));
        grade2Table.add(new Grade2Abbreviation().setWord("مؤمن").setSymbol("⠈⠳"));
        grade2Table.add(new Grade2Abbreviation().setWord("مسؤول").setSymbol("⠐⠳"));
        grade2Table.add(new Grade2Abbreviation().setWord("مؤلف").setSymbol("⠠⠳"));
        grade2Table.add(new Grade2Abbreviation().setWord("مؤسس").setSymbol("⠘⠳"));
        grade2Table.add(new Grade2Abbreviation().setWord("مؤتمر").setSymbol("⠰⠳"));
        grade2Table.add(new Grade2Abbreviation().setWord("مؤثر").setSymbol("⠸⠳"));
        grade2Table.add(new Grade2Abbreviation().setWord("إلا").setSymbol("⠽"));
        grade2Table.add(new Grade2Abbreviation().setWord("قائل").setSymbol("⠈⠽"));
        grade2Table.add(new Grade2Abbreviation().setWord("لأجل").setSymbol("⠐⠽"));
        grade2Table.add(new Grade2Abbreviation().setWord("سائل").setSymbol("⠠⠽"));
        grade2Table.add(new Grade2Abbreviation().setWord("صائم").setSymbol("⠘⠽"));
        grade2Table.add(new Grade2Abbreviation().setWord("شائع").setSymbol("⠰⠽"));
        grade2Table.add(new Grade2Abbreviation().setWord("فائز").setSymbol("⠸⠽"));
        grade2Table.add(new Grade2Abbreviation().setWord("كل").setSymbol("⠜"));
        grade2Table.add(new Grade2Abbreviation().setWord("آداب").setSymbol("⠈⠜"));
        grade2Table.add(new Grade2Abbreviation().setWord("آراء").setSymbol("⠐⠜"));
        grade2Table.add(new Grade2Abbreviation().setWord("آفاق").setSymbol("⠠⠜"));
        grade2Table.add(new Grade2Abbreviation().setWord("آخر").setSymbol("⠘⠜"));
        grade2Table.add(new Grade2Abbreviation().setWord("آثار").setSymbol("⠰⠜"));
        grade2Table.add(new Grade2Abbreviation().setWord("أيها").setSymbol("⠸⠜"));
        grade2Table.add(new Grade2Abbreviation().setWord("لم").setSymbol("⠑"));
        grade2Table.add(new Grade2Abbreviation().setWord("لم يعد").setSymbol("⠈⠑"));
        grade2Table.add(new Grade2Abbreviation().setWord("لم يكن").setSymbol("⠐⠑"));
        grade2Table.add(new Grade2Abbreviation().setWord("لم يتمكن").setSymbol("⠠⠑"));
        grade2Table.add(new Grade2Abbreviation().setWord("لم يلبث").setSymbol("⠘⠑"));
        grade2Table.add(new Grade2Abbreviation().setWord("لم يستطع").setSymbol("⠰⠑"));
        grade2Table.add(new Grade2Abbreviation().setWord("لم يزل").setSymbol("⠸⠑"));
        grade2Table.add(new Grade2Abbreviation().setWord("حيث").setSymbol("⠥"));
        grade2Table.add(new Grade2Abbreviation().setWord("حقوق").setSymbol("⠈⠥"));
        grade2Table.add(new Grade2Abbreviation().setWord("حاسب").setSymbol("⠐⠥"));
        grade2Table.add(new Grade2Abbreviation().setWord("حاسوب").setSymbol("⠠⠥"));
        grade2Table.add(new Grade2Abbreviation().setWord("حروف").setSymbol("⠘⠥"));
        grade2Table.add(new Grade2Abbreviation().setWord("حدود").setSymbol("⠰⠥"));
        grade2Table.add(new Grade2Abbreviation().setWord("دنيا").setSymbol("⠸⠥"));
        grade2Table.add(new Grade2Abbreviation().setWord("مع").setSymbol("⠆"));
        grade2Table.add(new Grade2Abbreviation().setWord("عن").setSymbol("⠔"));
        grade2Table.add(new Grade2Abbreviation().setWord("إلى").setSymbol("⠢"));
        grade2Table.add(new Grade2Abbreviation().setWord("لل").setSymbol("⠒"));
        grade2Table.add(new Grade2Abbreviation().setWord("ست").setSymbol("⠲"));
        grade2Table.add(new Grade2Abbreviation().setWord("في").setSymbol("⠖"));
        grade2Table.add(new Grade2Abbreviation().setWord("هو").setSymbol("⠦"));
        grade2Table.add(new Grade2Abbreviation().setWord("من").setSymbol("⠴"));
        grade2Table.add(new Grade2Abbreviation().setWord("متى").setSymbol("⠶"));
        grade2Table.add(new Grade2Abbreviation().setWord("ال").setSymbol("⠉"));
        grade2Table.add(new Grade2Abbreviation().setWord("اللائي").setSymbol("⠈⠉"));
        grade2Table.add(new Grade2Abbreviation().setWord("الذي").setSymbol("⠐⠉"));
        grade2Table.add(new Grade2Abbreviation().setWord("الناس").setSymbol("⠠⠉"));
        grade2Table.add(new Grade2Abbreviation().setWord("التي").setSymbol("⠘⠉"));
        grade2Table.add(new Grade2Abbreviation().setWord("اللاتي").setSymbol("⠰⠉"));
        grade2Table.add(new Grade2Abbreviation().setWord("اللذين").setSymbol("⠸⠉"));
        grade2Table.add(new Grade2Abbreviation().setWord("كان").setSymbol("⠛"));
        grade2Table.add(new Grade2Abbreviation().setWord("كون").setSymbol("⠈⠛"));
        grade2Table.add(new Grade2Abbreviation().setWord("كائن").setSymbol("⠐⠛"));
        grade2Table.add(new Grade2Abbreviation().setWord("كلم").setSymbol("⠠⠛"));
        grade2Table.add(new Grade2Abbreviation().setWord("كريم").setSymbol("⠘⠛"));
        grade2Table.add(new Grade2Abbreviation().setWord("تكوين").setSymbol("⠰⠛"));
        grade2Table.add(new Grade2Abbreviation().setWord("تكنولوجي").setSymbol("⠸⠛"));
        grade2Table.add(new Grade2Abbreviation().setWord("ما").setSymbol("⠏"));
        grade2Table.add(new Grade2Abbreviation().setWord("ما زال").setSymbol("⠈⠏"));
        grade2Table.add(new Grade2Abbreviation().setWord("ماذا").setSymbol("⠐⠏"));
        grade2Table.add(new Grade2Abbreviation().setWord("ما انفك").setSymbol("⠠⠏"));
        grade2Table.add(new Grade2Abbreviation().setWord("ما برح").setSymbol("⠘⠏"));
        grade2Table.add(new Grade2Abbreviation().setWord("ما دام").setSymbol("⠰⠏"));
        grade2Table.add(new Grade2Abbreviation().setWord("ما عدا").setSymbol("⠸⠏"));
        grade2Table.add(new Grade2Abbreviation().setWord("هم").setSymbol("⠻"));
        grade2Table.add(new Grade2Abbreviation().setWord("هاجر").setSymbol("⠈⠻"));
        grade2Table.add(new Grade2Abbreviation().setWord("هاتف").setSymbol("⠐⠻"));
        grade2Table.add(new Grade2Abbreviation().setWord("هامش").setSymbol("⠠⠻"));
        grade2Table.add(new Grade2Abbreviation().setWord("هندس").setSymbol("⠘⠻"));
        grade2Table.add(new Grade2Abbreviation().setWord("هيئة").setSymbol("⠰⠻"));
        grade2Table.add(new Grade2Abbreviation().setWord("هيمن").setSymbol("⠸⠻"));
        grade2Table.add(new Grade2Abbreviation().setWord("إذا").setSymbol("⠪"));
        grade2Table.add(new Grade2Abbreviation().setWord("إحصاء").setSymbol("⠈⠪"));
        grade2Table.add(new Grade2Abbreviation().setWord("إنسان").setSymbol("⠐⠪"));
        grade2Table.add(new Grade2Abbreviation().setWord("إنتاج").setSymbol("⠠⠪"));
        grade2Table.add(new Grade2Abbreviation().setWord("إسلام").setSymbol("⠘⠪"));
        grade2Table.add(new Grade2Abbreviation().setWord("إخراج").setSymbol("⠰⠪"));
        grade2Table.add(new Grade2Abbreviation().setWord("إيمان").setSymbol("⠸⠪"));
        grade2Table.add(new Grade2Abbreviation().setWord("ين").setSymbol("⠬"));
        grade2Table.add(new Grade2Abbreviation().setWord("ينطبق").setSymbol("⠈⠬"));
        grade2Table.add(new Grade2Abbreviation().setWord("ينمو").setSymbol("⠐⠬"));
        grade2Table.add(new Grade2Abbreviation().setWord("ينعكس").setSymbol("⠠⠬"));
        grade2Table.add(new Grade2Abbreviation().setWord("ينبغي").setSymbol("⠘⠬"));
        grade2Table.add(new Grade2Abbreviation().setWord("ينتشر").setSymbol("⠰⠬"));
        grade2Table.add(new Grade2Abbreviation().setWord("يندرج").setSymbol("⠸⠬"));
        grade2Table.add(new Grade2Abbreviation().setWord("وا").setSymbol("⠼"));
        grade2Table.add(new Grade2Abbreviation().setWord("وأما").setSymbol("⠼"));
        grade2Table.add(new Grade2Abbreviation().setWord("ية").setSymbol("⠘"));
        grade2Table.add(new Grade2Abbreviation().setWord("ات").setSymbol("⠨"));
        grade2Table.add(new Grade2Abbreviation().setWord("ون").setSymbol("⠸"));

    }

    public static Set<Grade2Abbreviation> getTable() {
        return Collections.unmodifiableSet(grade2Table);
    }
}
