package utils.grade2;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * Created by hosainfathelbab on 4/11/15.
 */
public class Constants {
    public static final Set<Character> punctuation = new HashSet<Character>();
    public static final Set<Character> tashkeel = new HashSet<Character>();
    public static final Set<String> objectPronouns = new HashSet<String>();
    public static final Map<String, String> brailleSymbolMapping = new HashMap<String, String>(63);
    public static final Map<String, String> brailleSymbolReverseMapping = new HashMap<String, String>(63);
    public static final char SHADDA = 'ّ';

    static {
        tashkeel.add('َ');
        tashkeel.add('ِ');
        tashkeel.add('ُ');
        tashkeel.add('ً');
        tashkeel.add('ٍ');
        tashkeel.add('ٌ');
        tashkeel.add('ّ');
        tashkeel.add('ْ');

        objectPronouns.add("ني");
        objectPronouns.add("ك");
        objectPronouns.add("ه");
        objectPronouns.add("ها");
        objectPronouns.add("نا");
        objectPronouns.add("كما");
        objectPronouns.add("هما");
        objectPronouns.add("نا");
        objectPronouns.add("كم");
        objectPronouns.add("كن");
        objectPronouns.add("هم");
        objectPronouns.add("هن");
        objectPronouns.add("هم");

        punctuation.add(',');
        punctuation.add('[');
        punctuation.add(']');
        punctuation.add('{');
        punctuation.add('}');
        punctuation.add('(');
        punctuation.add(')');
        punctuation.add('<');
        punctuation.add('>');
        punctuation.add(':');
        punctuation.add('-');
        punctuation.add('_');
        punctuation.add('.');
        punctuation.add('!');
        punctuation.add('?');
        punctuation.add('\'');
        punctuation.add('\"');
        punctuation.add(';');
        punctuation.add('.');
        punctuation.add('،');
        punctuation.add(' ');
        punctuation.add('!');
        punctuation.add('\n');
        punctuation.add('.');

        brailleSymbolReverseMapping.put("⠁","1");
        brailleSymbolReverseMapping.put("⠂","2");
        brailleSymbolReverseMapping.put("⠃","12");
        brailleSymbolReverseMapping.put("⠄","3");
        brailleSymbolReverseMapping.put("⠅","13");
        brailleSymbolReverseMapping.put("⠆","23");
        brailleSymbolReverseMapping.put("⠇","123");
        brailleSymbolReverseMapping.put("⠈","4");
        brailleSymbolReverseMapping.put("⠉","14");
        brailleSymbolReverseMapping.put("⠊","24");
        brailleSymbolReverseMapping.put("⠋","124");
        brailleSymbolReverseMapping.put("⠌","34");
        brailleSymbolReverseMapping.put("⠍","134");
        brailleSymbolReverseMapping.put("⠎","234");
        brailleSymbolReverseMapping.put("⠏","1234");
        brailleSymbolReverseMapping.put("⠐","5");
        brailleSymbolReverseMapping.put("⠑","15");
        brailleSymbolReverseMapping.put("⠒","25");
        brailleSymbolReverseMapping.put("⠓","125");
        brailleSymbolReverseMapping.put("⠔","35");
        brailleSymbolReverseMapping.put("⠕","135");
        brailleSymbolReverseMapping.put("⠖","235");
        brailleSymbolReverseMapping.put("⠗","1235");
        brailleSymbolReverseMapping.put("⠘","45");
        brailleSymbolReverseMapping.put("⠙","145");
        brailleSymbolReverseMapping.put("⠚","245");
        brailleSymbolReverseMapping.put("⠛","1245");
        brailleSymbolReverseMapping.put("⠜","345");
        brailleSymbolReverseMapping.put("⠝","1345");
        brailleSymbolReverseMapping.put("⠞","2345");
        brailleSymbolReverseMapping.put("⠟","12345");
        brailleSymbolReverseMapping.put("⠠","6");
        brailleSymbolReverseMapping.put("⠡","16");
        brailleSymbolReverseMapping.put("⠢","26");
        brailleSymbolReverseMapping.put("⠣","126");
        brailleSymbolReverseMapping.put("⠤","36");
        brailleSymbolReverseMapping.put("⠥","136");
        brailleSymbolReverseMapping.put("⠦","236");
        brailleSymbolReverseMapping.put("⠧","1236");
        brailleSymbolReverseMapping.put("⠨","46");
        brailleSymbolReverseMapping.put("⠩","146");
        brailleSymbolReverseMapping.put("⠪","246");
        brailleSymbolReverseMapping.put("⠫","1246");
        brailleSymbolReverseMapping.put("⠬","346");
        brailleSymbolReverseMapping.put("⠭","1346");
        brailleSymbolReverseMapping.put("⠮","2346");
        brailleSymbolReverseMapping.put("⠯","12346");
        brailleSymbolReverseMapping.put("⠰","56");
        brailleSymbolReverseMapping.put("⠱","156");
        brailleSymbolReverseMapping.put("⠲","256");
        brailleSymbolReverseMapping.put("⠳","1256");
        brailleSymbolReverseMapping.put("⠴","356");
        brailleSymbolReverseMapping.put("⠵","1356");
        brailleSymbolReverseMapping.put("⠶","2356");
        brailleSymbolReverseMapping.put("⠷","12356");
        brailleSymbolReverseMapping.put("⠸","456");
        brailleSymbolReverseMapping.put("⠹","1456");
        brailleSymbolReverseMapping.put("⠺","2456");
        brailleSymbolReverseMapping.put("⠻","12456");
        brailleSymbolReverseMapping.put("⠼","3456");
        brailleSymbolReverseMapping.put("⠽","13456");
        brailleSymbolReverseMapping.put("⠾","23456");
        brailleSymbolReverseMapping.put("⠿","123456");

        brailleSymbolMapping.put("1","⠁");
        brailleSymbolMapping.put("2","⠂");
        brailleSymbolMapping.put("12","⠃");
        brailleSymbolMapping.put("3","⠄");
        brailleSymbolMapping.put("13","⠅");
        brailleSymbolMapping.put("23","⠆");
        brailleSymbolMapping.put("123","⠇");
        brailleSymbolMapping.put("4","⠈");
        brailleSymbolMapping.put("14","⠉");
        brailleSymbolMapping.put("24","⠊");
        brailleSymbolMapping.put("124","⠋");
        brailleSymbolMapping.put("34","⠌");
        brailleSymbolMapping.put("134","⠍");
        brailleSymbolMapping.put("234","⠎");
        brailleSymbolMapping.put("1234","⠏");
        brailleSymbolMapping.put("5","⠐");
        brailleSymbolMapping.put("15","⠑");
        brailleSymbolMapping.put("25","⠒");
        brailleSymbolMapping.put("125","⠓");
        brailleSymbolMapping.put("35","⠔");
        brailleSymbolMapping.put("135","⠕");
        brailleSymbolMapping.put("235","⠖");
        brailleSymbolMapping.put("1235","⠗");
        brailleSymbolMapping.put("45","⠘");
        brailleSymbolMapping.put("145","⠙");
        brailleSymbolMapping.put("245","⠚");
        brailleSymbolMapping.put("1245","⠛");
        brailleSymbolMapping.put("345","⠜");
        brailleSymbolMapping.put("1345","⠝");
        brailleSymbolMapping.put("2345","⠞");
        brailleSymbolMapping.put("12345","⠟");
        brailleSymbolMapping.put("6","⠠");
        brailleSymbolMapping.put("16","⠡");
        brailleSymbolMapping.put("26","⠢");
        brailleSymbolMapping.put("126","⠣");
        brailleSymbolMapping.put("36","⠤");
        brailleSymbolMapping.put("136","⠥");
        brailleSymbolMapping.put("236","⠦");
        brailleSymbolMapping.put("1236","⠧");
        brailleSymbolMapping.put("46","⠨");
        brailleSymbolMapping.put("146","⠩");
        brailleSymbolMapping.put("246","⠪");
        brailleSymbolMapping.put("1246","⠫");
        brailleSymbolMapping.put("346","⠬");
        brailleSymbolMapping.put("1346","⠭");
        brailleSymbolMapping.put("2346","⠮");
        brailleSymbolMapping.put("12346","⠯");
        brailleSymbolMapping.put("56","⠰");
        brailleSymbolMapping.put("156","⠱");
        brailleSymbolMapping.put("256","⠲");
        brailleSymbolMapping.put("1256","⠳");
        brailleSymbolMapping.put("356","⠴");
        brailleSymbolMapping.put("1356","⠵");
        brailleSymbolMapping.put("2356","⠶");
        brailleSymbolMapping.put("12356","⠷");
        brailleSymbolMapping.put("456","⠸");
        brailleSymbolMapping.put("1456","⠹");
        brailleSymbolMapping.put("2456","⠺");
        brailleSymbolMapping.put("12456","⠻");
        brailleSymbolMapping.put("3456","⠼");
        brailleSymbolMapping.put("13456","⠽");
        brailleSymbolMapping.put("23456","⠾");
        brailleSymbolMapping.put("123456","⠿");
    }
}
